channels:
- conda-forge
dependencies:
- bagofholding =0.1.12
- bidict =0.23.1
- cloudpickle =3.1.2
- executorlib =1.10.1
- fleche =0.19.2
- flowrep =0.5.2
- graphviz =12.2.1
- hatchling =1.30.1
- hatch-vcs =0.5.0
- networkx =3.6.1
- pandas =3.0.3
- pint =0.25.3
- pyiron_snippets =1.4.0
- python >=3.11,<3.14
- python-graphviz =0.21
- rdflib =7.6.0
- semantikon =1.3.2
- toposort =1.10
- typeguard =4.5.2
- python-workflow-definition =0.1.5
