#!/bin/bash
pip install . --no-deps --no-build-isolation

# Save the stuff we actually need for binder
KEEP=("notebooks")
mkdir -p ${HOME}/.temp_keep
for item in "${KEEP[@]}"; do
    [ -e "${HOME}/${item}" ] && mv "${HOME}/${item}" ${HOME}/.temp_keep/
done

# Now clean up everything else
find ${HOME} -mindepth 1 -maxdepth 1 ! -name '.temp_keep' -exec rm -rf {} +

# Restore the kept material
mv ${HOME}/.temp_keep/* ${HOME}/
rmdir ${HOME}/.temp_keep

# Manipulate kept material
mv ${HOME}/notebooks/* ${HOME}
rmdir ${HOME}/notebooks
