channels:
- conda-forge
dependencies:
- executorlib =1.10.2
- flowrep =0.6.2
- hatchling =1.31.0
- hatch-vcs =0.5.0
- pint =0.25.3
- pyiron_snippets =1.5.0
- python >=3.11,<3.15
- rdflib =7.6.0
- semantikon =1.4.2
- typeguard =4.5.2
