channels:
  - conda-forge
dependencies:
  - ase =3.22.1
  - atomistics =0.1.23
  - lammps
  - matgl =0.9.2
  - pandas =2.2.0
  - phonopy =2.21.0
  - pyiron_atomistics =0.4.15
  - pyiron_contrib =0.1.15
  - pyiron-data =0.0.27
  - numpy =1.26.4