# Trying to track down the recent upstream breaks of building docs

name: setup-miniforge then unit tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pyiron/actions/build-docs@use_miniconda
        with:
          python-version: '3.12'
