# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-main-Pull-all

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  slurm-interruption:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/slurm-test.yml
    with:
      mode: interrupt

  slurm-discovery:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/slurm-test.yml
    with:
      mode: discover
